# Generated by Django 5.0.7 on 2024-09-02 11:12

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='文章的内容'),
        ),
    ]
